name: Quality
on:
  workflow_call:
    inputs:
      linter:
        required: true
        type: string
      arguments:
        required: false
        type: string
      pre_run:
        required: false
        type: string
      post_run:
        required: false
        type: string

jobs:
  Quality:
    runs-on: ubuntu-20.04
    environment: docker
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    container:
      image: pawelekg95/rethreadme:latest
      credentials:
        username: ${{ env.DOCKER_LOGIN }}
        password: ${{ env.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        run: |
          ${{ inputs.pre_run }}
          ${{ inputs.linter }} ${{ inputs.arguments }}
          ${{ inputs.post_run }}
