name: ReThreadMe_CI
on: push

jobs:
  # Prepare Environment
  ReThreadMe_docker:
    name: ReThreadMe_docker
    uses: ./.github/workflows/environment.yml
    with:
      image: rethreadme
    secrets: inherit

  # Build test
  Build_thread_test_gcc_debug:
    name: Build_thread_test_gcc_debug
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_debug
      app: Build_thread_test_gcc_debug
    secrets: inherit

  Build_thread_test_gcc_release:
    name: Build_thread_test_gcc_release
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_release
      app: Build_thread_test_gcc_release
    secrets: inherit

  Build_thread_test_clang_debug:
    name: Build_thread_test_clang_debug
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_clang_debug
      app: Build_thread_test_clang_debug
    secrets: inherit

  Build_thread_test_clang_release:
    name: Build_thread_test_clang_release
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_clang_release
      app: Build_thread_test_clang_release
    secrets: inherit

  # Build sanitized test
  Build_thread_test_gcc_debug_lsan:
    name: Build_thread_test_gcc_debug_lsan
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_debug_lsan
      app: Build_thread_test_gcc_debug_lsan
    secrets: inherit

  Build_thread_test_gcc_debug_asan:
    name: Build_thread_test_gcc_debug_asan
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_debug_asan
      app: Build_thread_test_gcc_debug_asan
    secrets: inherit

  Build_thread_test_gcc_debug_ubsan:
    name: Build_thread_test_gcc_debug_ubsan
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_debug_ubsan
      app: Build_thread_test_gcc_debug_ubsan
    secrets: inherit

  Build_thread_test_gcc_debug_tsan:
    name: Build_thread_test_gcc_debug_tsan
    needs: ReThreadMe_docker
    uses: ./.github/workflows/build.yml
    with:
      preset: thread_test_gcc_debug_tsan
      app: Build_thread_test_gcc_debug_tsan
    secrets: inherit

  # Run test
  Thread_test:
    name: Thread_test
    needs: Build_thread_test_gcc_debug
    uses: ./.github/workflows/run.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug-${{ github.sha }}
      app: ./one-variable-example
    secrets: inherit

  # Run sanitized test
  Thread_test_lsan:
    name: Thread_test_lsan
    needs: Build_thread_test_gcc_debug_lsan
    uses: ./.github/workflows/run.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug_lsan-${{ github.sha }}
      app: ./test
    secrets: inherit

  Thread_test_asan:
    name: Thread_test_asan
    needs: Build_thread_test_gcc_debug_asan
    uses: ./.github/workflows/run.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug_asan-${{ github.sha }}
      app: ./test
    secrets: inherit

  Thread_test_tsan:
    name: Thread_test_tsan
    needs: Build_thread_test_gcc_debug_tsan
    uses: ./.github/workflows/run.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug_tsan-${{ github.sha }}
      app: ./test
    secrets: inherit

  Thread_test_ubsan:
    name: Thread_test_ubsan
    needs: Build_thread_test_gcc_debug_ubsan
    uses: ./.github/workflows/run.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug_ubsan-${{ github.sha }}
      app: ./test
    secrets: inherit

  # Valgrind test
  Thread_test_valgrind:
    name: Thread_test_valgrind
    needs: Thread_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_thread_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  # Quality
  Clang-format:
    needs: ReThreadMe_docker
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"
      linter: run-clang-format.py
      arguments: -ir lib test
    secrets: inherit

  Clang-tidy:
    needs: ReThreadMe_docker
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"; rm -rf ./cmake-build; mkdir ./cmake-build; cd ./cmake-build; cmake .. --preset thread_test_clang_debug
      linter: run-clang-tidy
    secrets: inherit

  Dockerfiles-hadolint:
    needs: ReThreadMe_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: hadolint
      arguments: .github/*.dockerfile
    secrets: inherit

  Pylint:
    needs: ReThreadMe_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: pylint
      arguments: $(find . -name *.py)
    secrets: inherit
